### ISSUE TITLE
Issues running Beaconcha.in explorer web app

### ISSUE THREAD

**Issue by mxmar** [gobitfly/eth2-beaconchain-explorer#1985]
**Describe the bug**
I'm getting some issues while running `Beaconcha.in` explorer in our infrastructure. We are using Google Bigtable. I'm using the latest `tables.sql` from this repostory. I'm using `init-bigtable.sh` to prepare our Google Bigtable from [Ethereum's Ansible repo](https://github.com/ethpandaops/ansible-collection-general/blob/master/roles/beaconchain_explorer_aio/files/bigtable/init-bigtable.sh). I've made some modifications to it, you can see below. The question is how I can spin my beaconcha.in explorer? Is it possible? What files are outdated? (`tables.sql` or/and Bigtable's script?)

**To Reproduce**
1. Have an Ubuntu instance with docker and docker-compose installed
2. Prepare your Google Bigtable (create tables, families etc) - It's expensive, I know! You can see [Bogota workshop](https://github.com/gobitfly/eth-explorer-workshop-bogota) and use `littlebigtable` solution too (very low performance)
3. Prepare your `exporter` and `frontend` configurations (DBs, Erigon, Geth endpoints etc)
4. Run `docker-compose.yaml`
5. See errors in `exporter` and `frontend` services

**Expected behavior**
Have a solution for this - Updated `tables.sql`, Bigtable families, series? or valid configurations to run `v1.16.1` explorer.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: `Ubuntu 21.10 x64` -> GCE VM
 - Browser `Firefox Browser` `v111.0`
 - Version `Beaconcha.in` `v1.16.1`

**Phone (please complete the following information):**
None

**Additional context**

**exporter service:**
```sh
time="2023-03-23T12:11:31Z" level=info msg="Tiered Cache initialized. Latest finalized epoch: 0"
time="2023-03-23T12:11:31Z" level=info msg="initializing geth client at http://address_here:8545" module=rpc
time="2023-03-23T12:11:31Z" level=info msg="database connection established"
time="2023-03-23T12:11:31Z" level=info msg="initializing prices"
time="2023-03-23T12:11:31Z" level=info msg="prices initialized"
time="2023-03-23T12:11:31Z" level=info msg="initializing ethclients"
time="2023-03-23T12:11:31Z" level=info msg="ethclients initialized"
time="2023-03-23T12:11:31Z" level=info msg="frontend database connection established"
time="2023-03-23T12:11:31Z" level=info msg="Updating ETH Clients Information" module=ethClients
time="2023-03-23T12:11:31Z" level=fatal msg="getting previous head epoch from db error" cs_file=exporter.go cs_function=eth2-exporter/exporter.networkLivenessUpdater cs_line=647 error="ERROR: relation \"network_liveness\" does not exist (SQLSTATE 42P01)" error type="*pgconn.PgError"
time="2023-03-23T12:11:58Z" level=info msg="compile time check completed" module=templates
time="2023-03-23T12:11:58Z" level=info msg="did init config" configName=myDevnet depositChainID=222222 depositContractAddress=0x0000000000000000000000000000000000004242 depositNetworkID=222222 genesisTimestamp=1678439500 genesisValidatorsRoot=0x74ad65628c3649557157558f0c7a6f865d7f055bc31c849755153a8ed83e645a
time="2023-03-23T12:11:58Z" level=info msg=starting chainName=myDevnet config=/configs/explorer.config.yml version=v1.16.1
time="2023-03-23T12:11:58Z" level=info msg="initializing erigon client at http://address_here:8545" module=rpc
time="2023-03-23T12:11:58Z" level=error msg="error retrieving latestFinalized for key: 222222:frontend:latestFinalized from cache: redis: nil" module=services
```

**frontend service:**
```sh
time="2023-03-23T12:13:53Z" level=info msg="compile time check completed" module=templates
time="2023-03-23T12:13:53Z" level=info msg="did init config" configName=myDevnet depositChainID=222222 depositContractAddress=0x0000000000000000000000000000000000004242 depositNetworkID=222222 genesisTimestamp=1678439500 genesisValidatorsRoot=0x74ad65628c3649557157558f0c7a6f865d7f055bc31c849755153a8ed83e645a
time="2023-03-23T12:13:53Z" level=info msg=starting chainName=myDevnet config=/configs/frontend_config.yml version=v1.16.1
time="2023-03-23T12:13:53Z" level=info msg="initializing erigon client at http://address_here:8545" module=rpc
time="2023-03-23T12:13:53Z" level=error msg="error retrieving latestFinalized for key: 222222:frontend:latestFinalized from cache: redis: nil" module=services
time="2023-03-23T12:13:53Z" level=info msg="Tiered Cache initialized. Latest finalized epoch: 0"
time="2023-03-23T12:13:53Z" level=info msg="initializing geth client at http://address_here:8545" module=rpc
time="2023-03-23T12:13:53Z" level=info msg="database connection established"
time="2023-03-23T12:13:53Z" level=fatal msg="getting previous head epoch from db error" cs_file=exporter.go cs_function=eth2-exporter/exporter.networkLivenessUpdater cs_line=647 error="ERROR: relation \"network_liveness\" does not exist (SQLSTATE 42P01)" error type="*pgconn.PgError"
```

**docker-compose file:**
```yml
version: '3.4'
services:
  redis:
    image: redis:7
    restart: always
    volumes:
      - db:/data
      - $CONFIGS_VOLUME:/configs
    networks:
      - custom-bridge
    ports:
      - 6379:6379
    expose:
      - 6379

  postgres:
    image: postgres:14.0
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - PGDATA=/postgresql/data/02152023
    volumes:
      - db:/postgresql/data
      - $CONFIGS_VOLUME/tables.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - custom-bridge
    ports:
      - 5432:5432
    expose:
      - 5432

  exporter:
    container_name: beaconchain_exporter
    image: gobitfly/eth2-beaconchain-explorer:v1.16.1
    stop_grace_period: 5m
    restart: always
    command:
      - /app/explorer
      - -config=/configs/explorer.config.yml
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $CONFIGS_VOLUME:/configs
      - db:/data
    environment:
      - INDEXER_ENABLED=true
    networks:
      - custom-bridge
    ports:
      - 8082:8082
    expose:
      - 8082

  eth1indexer:
    container_name: beaconchain_eth1indexer
    image: gobitfly/eth2-beaconchain-explorer:v1.16.1
    stop_grace_period: 5m
    restart: always
    command:
      - /app/eth1indexer
      - -config=/configs/explorer.config.yml
      - -bigtable.project=test-network-222222
      - -bigtable.instance=test-devnet-222222
      - -erigon=ws://address_here:8545
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $CONFIGS_VOLUME:/configs
      - $EXECUTION_DATA_VOLUME:/geth
      - db:/data
    networks:
      - custom-bridge

  statistics:
    container_name: beaconchain_statistics
    image: gobitfly/eth2-beaconchain-explorer:v1.16.1
    stop_grace_period: 5m
    restart: always
    command:
      - /app/statistics
      - -config=/configs/explorer.config.yml
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $CONFIGS_VOLUME:/configs
      - db:/data
    environment:
      - INDEXER_ENABLED=false
    networks:
      - custom-bridge

  frontend-updater:
    container_name: beaconchain_frontend_updater
    image: gobitfly/eth2-beaconchain-explorer:v1.16.1
    stop_grace_period: 5m
    restart: always
    command:
      - /app/frontend-data-updater
      - -config=/configs/frontend_config.yml
    environment:
      - FRONTEND_ENABLED=true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $CONFIGS_VOLUME:/configs
      - db:/data
    networks:
      - custom-bridge

  frontend:
    container_name: beaconchain_frontend
    image: gobitfly/eth2-beaconchain-explorer:v1.16.1
    stop_grace_period: 5m
    restart: always
    command:
      - /app/explorer
      - -config=/configs/frontend_config.yml
    environment:
      - FRONTEND_ENABLED=true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $CONFIGS_VOLUME:/configs
      - db:/data"
    networks:
      - custom-bridge
    ports:
      - 80:8080

volumes:
  db:

networks:
  custom-bridge:
    name: custom-net
    driver: bridge
```

**frontend config file:**
```yml
readerDatabase:
  name: db
  host: postgres
  port: 5432
  user: postgres
  password: pass
  
writerDatabase:
  name: db
  host: postgres
  port: 5432
  user: postgres
  password: pass
  
bigtable:
  project: test-network-222222
  instance: test-devnet-222222
  
# Chain network configuration
chain:
  slotsPerEpoch: 32
  secondsPerSlot: 12
  minGenesisActiveValidatorCount: 120
  configPath: /configs/config.yaml
  genesisTimestamp: 1678439500
  genesisValidatorsRoot: 0x74ad65628c3649557157558f0c7a6f865d7f055bc31c849755153a8ed83e645a

lastAttestationCachePath: "/data/lastAttestationCache"
eth1ErigonEndpoint: 'http://address_here:8545'
eth1GethEndpoint: 'http://address_here:8545'
redisCacheEndpoint: 'redis:6379'
tieredCacheProvider: 'redis'

frontend:
  enabled: true
  siteDomain: "localhost:8080"
  siteName: "Consensus Explorer" # Name of the site, displayed in the title tag
  siteSubtitle: "Consensus Explorer" # Subtitle shown on the main page
  server:
    host: '0.0.0.0' # Address to listen on
    port: '8080' # Port to listen on
  readerDatabase:
    name: db
    host: postgres
    port: 5432
    user: postgres
    password: pass
  writerDatabase:
    name: db
    host: postgres
    port: 5432
    user: postgres
    password: pass
  sessionSecret: "11111111111111111111111111111111"
  csrfAuthKey: '0243456789abcdef000000000000000000000000000000000000000000000000'
  jwtSigningSecret: "0243456789abcdef000000000000000000000000000000000000000000000000"
  jwtIssuer: "localblockexplorer"
  jwtValidityInMinutes: 30
  slotViz:
    enabled: false
    hardforkEpoch: 0
    
indexer:
  enabled: true
  #indexMissingEpochsOnStartup: true # Check for missing epochs and export them after startup
  #updateAllEpochStatistics: true
  #fixCanonOnStartup: true
  #fullIndexOnStartup: true
  #checkAllBlocksOnStartup: true
  node:
    host: '222222' # Address of the backend node
    port: "4000" # GRPC port of the Prysm node
    type: "lighthouse" # can be either prysm or lighthouse
  eth1DepositContractAddress: '0x0000000000000000000000000000000000004242'
  eth1DepositContractFirstBlock: 0
```

**exporter config file:**
```yml
readerDatabase:
  name: db
  host: postgres
  port: 5432
  user: postgres
  password: pass
  
writerDatabase:
  name: db
  host: postgres
  port: 5432
  user: postgres
  password: pass
  
bigtable:
  project: test-network-222222
  instance: test-devnet-222222

# Chain network configuration
chain:
  slotsPerEpoch: 32
  secondsPerSlot: 12
  minGenesisActiveValidatorCount: 120
  configPath: /configs/config.yaml
  genesisTimestamp: 1678439500
  genesisValidatorsRoot: 0x74ad65628c3649557157558f0c7a6f865d7f055bc31c849755153a8ed83e645a

lastAttestationCachePath: "/data/lastAttestationCache"
eth1ErigonEndpoint: 'http://address_here:8545'
eth1GethEndpoint: 'http://address_here:8545'
redisCacheEndpoint: 'redis:6379'
tieredCacheProvider: 'redis'

# Frontend config
frontend:
  enabled: true # Enable or disable to web frontend
  siteName: "Consensus Explorer" # Name of the site, displayed in the title tag
  siteSubtitle: "Consensus Explorer" # Subtitle shown on the main page
  csrfAuthKey: '0243456789abcdef000000000000000000000000000000000000000000000000'
  jwtSigningSecret: "0243456789abcdef000000000000000000000000000000000000000000000000"
  jwtIssuer: "localblockexplorer"
  jwtValidityInMinutes: 30
  server:
    host: "0.0.0.0" # Address to listen on
    port: "3333" # Port to listen on
  readerDatabase:
    name: db
    host: postgres
    port: 5432
    user: postgres
    password: pass
  writerDatabase:
    name: db
    host: postgres
    port: 5432
    user: postgres
    password: pass

# Indexer config
indexer:
  enabled: true # Enable or disable the indexing service
  fullIndexOnStartup: true # Perform a one time full db index on startup
  indexMissingEpochsOnStartup: true # Check for missing epochs and export them after startup
  node:
    host: 'address_here' # Address of the backend node
    port: "4000" # GRPC port of the Prysm node
    type: "lighthouse" # can be either prysm or lighthouse
    pageSize: 100 # the amount of entries to fetch per paged rpc call
  eth1Endpoint: 'http://address_here:8545'
  eth1DepositContractAddress: '0x0000000000000000000000000000000000004242'
  # Note: 0 is correct, but due to an underflow bug (being fixed), doesn't work.
  eth1DepositContractFirstBlock: 0
```

**init-bigtable.sh**
```sh
#!/usr/bin/env bash

export BIGTABLE_EMULATOR_HOST="bigtable:9009"
INSTANCE="test-devnet-222222"
PROJECT="test-network-222222"

cbt -project $PROJECT -instance $INSTANCE createtable beaconchain
cbt -project $PROJECT -instance $INSTANCE createtable blocks
cbt -project $PROJECT -instance $INSTANCE createtable cache
cbt -project $PROJECT -instance $INSTANCE createtable data
cbt -project $PROJECT -instance $INSTANCE createtable metadata
cbt -project $PROJECT -instance $INSTANCE createtable metadata_updates
cbt -project $PROJECT -instance $INSTANCE createtable charts

cbt -project $PROJECT -instance $INSTANCE createfamily beaconchain at
cbt -project $PROJECT -instance $INSTANCE createfamily beaconchain pr
cbt -project $PROJECT -instance $INSTANCE createfamily beaconchain sc
cbt -project $PROJECT -instance $INSTANCE createfamily beaconchain vb

cbt -project $PROJECT -instance $INSTANCE createfamily blocks default

cbt -project $PROJECT -instance $INSTANCE createfamily cache 10_min
cbt -project $PROJECT -instance $INSTANCE createfamily cache 1_day
cbt -project $PROJECT -instance $INSTANCE createfamily cache 1_hour

cbt -project $PROJECT -instance $INSTANCE createfamily metadata a
cbt -project $PROJECT -instance $INSTANCE createfamily metadata c
cbt -project $PROJECT -instance $INSTANCE createfamily metadata erc1155
cbt -project $PROJECT -instance $INSTANCE createfamily metadata erc20
cbt -project $PROJECT -instance $INSTANCE createfamily metadata erc721

cbt -project $PROJECT -instance $INSTANCE createfamily metadata_updates blocks
cbt -project $PROJECT -instance $INSTANCE createfamily metadata_updates f

cbt -project $PROJECT -instance $INSTANCE createfamily data c
cbt -project $PROJECT -instance $INSTANCE createfamily data f

cbt -project $PROJECT -instance $INSTANCE createfamily charts series
```
