### ISSUE TITLE
Does not run even when providing both Erigon and Geth endpoints

### ISSUE THREAD

**Issue by ybstaked** [gobitfly/eth2-beaconchain-explorer#2291]
Does not start and fails with:
```
time="2023-06-11T16:02:59Z" level=info msg="initializing erigon client at " module=rpc
time="2023-06-11T16:02:59Z" level=fatal msg="error initializing erigon client: error dialing rpc node: dial unix: missing address"
```

Here's config used
```
indexer:
  enabled: true
  eth1DepositContractAddress: 0x00000000219ab540356cBB839Cbe05303d7705Fa
  eth1DepositContractFirstBlock: 1
  eth1Endpoint: http://erigon-node.erigon:8545
  eth1ErigonEndpoint: http://erigon-node.erigon:8545
  eth1GethEndpoint: http://el-geth-mainnet-0-node-svc.ethereum-mev:8545
  fullIndexOnStartup: false
  indexMissingEpochsOnStartup: false
  node:
    host: cl-lighthouse-mainnet-0.ethereum-mev
    pageSize: 500
    port: "5052"
    type: lighthouse
```

<img width="1726" alt="image" src="https://github.com/gobitfly/eth2-beaconchain-explorer/assets/85460995/2a87d109-79b7-410f-94db-9d748b669f5d">
