### ISSUE TITLE
missing config pectraWithdrawalRequestContractAddress

### ISSUE THREAD

**Issue by pradavc** [gobitfly/eth2-beaconchain-explorer#3045]
**Describe the bug**
When running the beaconchain explorer in kurtosis, a "missing config pectraWithdrawalRequestContractAddress" error  is shown.

**To Reproduce**
Run beaconchain explorer using kurtosis: https://github.com/ethpandaops/ethereum-package/blob/main/src/full_beaconchain/full_beaconchain_launcher.star

**Screenshots**

<img width="394" alt="Image" src="https://github.com/user-attachments/assets/ee34f581-0299-49e5-a366-7b769f2327ba" />

Do you have any idea on how to solve this issue?
Thanks in advance.

**Comment by pradavc** [comment]
Solved adding:

```
chain:
  clConfigPath: 'node'
  elConfigPath: '/network-configs/genesis.json'
  pectraWithdrawalRequestContractAddress: '0x00000961Ef480Eb55e80D19ad83579A64c007002'
  pectraConsolidationRequestContractAddress: '0x0000BBdDc7CE488642fb579F8B00f3a590007251'
```

To the file github.com/ethpandaops/ethereum-package/static_files/full-beaconchain-config/config.yaml.tmpl.
