### ISSUE TITLE
Failed to run SQL migration with beaconchain-schema-initializer

### ISSUE THREAD

**Issue by pradavc** [gobitfly/eth2-beaconchain-explorer#3048]
**Describe the bug**
The SQL migration fails when using kurtosis to run the explorer.

**To Reproduce**
1. Clone the repo `https://github.com/ethpandaops/ethereum-package`
2. Make the following changes to the file `network_params.yaml`:

```
    el_extra_params: ["--gcmode=archive", "--syncmode=full", "--state.scheme=hash", "--http.api='admin,eth,net,debug,txpool'", "--http.corsdomain=*"]
```

```
    cl_extra_params: ["--reconstruct-historic-states"]
```

```
additional_services: 
  - full_beaconchain_explorer
```

3. Edit the file `static_files/full-beaconchain-config/config.yaml.tmpl` and add:
```
chain:
  clConfigPath: 'node'
  elConfigPath: '/network-configs/genesis.json'
  pectraWithdrawalRequestContractAddress: '0x00000961Ef480Eb55e80D19ad83579A64c007002'
  pectraConsolidationRequestContractAddress: '0x0000BBdDc7CE488642fb579F8B00f3a590007251'
```

To prevent the error `missing config pectraWithdrawalRequestContractAddress`.

4. Run `kurtosis run . --enclave dev --args-file network_params.yaml`.
5. See error:

<img width="1493" alt="Image" src="https://github.com/user-attachments/assets/b91d6586-130f-4f39-88bb-e554f793e628" />

**Expected behavior**
The beaconchain explorer should run and execute the migration successfully.
